import type { NextPage } from 'next';
import Head from 'next/head';
import { Feature } from '../components/Home/Feature';
import { Footer } from '../components/Home/Footer';
import { Hero } from '../components/Home/Hero';
import { Navbar } from '../components/Home/Navbar';
import { Pricing } from '../components/Home/Pricing';
import { Statistic } from '../components/Home/Statistic';
import { Step } from '../components/Home/Step';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Full Stack NextJS Boilerplate</title>
        <meta
          name="description"
          content="Generated by create fullstack next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Hero />

      <Statistic />

      <Feature />

      <Step />

      <Pricing />

      <Footer />
    </div>
  );
};

export default Home;
